#!/bin/bash 

progl() {
    export LD_LIBRARY_PATH="/opt/amdgpu-pro/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
    export LIBGL_DRIVERS_PATH="/opt/amdgpu-pro/lib/x86_64-linux-gnu/dri/"
    #export dri_driver="amdgpu"	
}


if [[ $(basename $0) == progl ]]; then
    progl
else
    echo "Unknown function"
    exit 1
fi

# applied variables, now execute the rest of the command
"$@"
